version: '3.8'
services:
  app:
    build:
      context: ./docker/ci4
    volumes:
      - .:/var/www/html
    environment:
      CI_ENVIRONMENT: production
    networks:
      - app-network

  nginx:
    image: nginx:alpine # Using the alpine version for smaller size
    volumes:
      - ./public:/var/www/html/public
      - ./docker/nginx/nginx.prod.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - app

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ${MYSQL_PROD_DATABASE}
      MYSQL_USER: ${MYSQL_PROD_USER}
      MYSQL_PASSWORD: ${MYSQL_PROD_PASSWORD}
    networks:
      - app-network

  redis:
    image: redis:alpine # Using the alpine version for smaller size
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
