version: '3.8'
services:
  app:
    build:
      context: ./docker/ci4
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    environment:
      CI_ENVIRONMENT: development
      DB_HOST: mysql
      DB_DATABASE: ci4
      DB_USERNAME: root
      DB_PASSWORD: root
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes: 
      - ./public:/var/www/html/public  
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf  
    depends_on:
      - app
    networks:
      - app-network

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ci4
      MYSQL_ROOT_PASSWORD: root

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
