version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: docker/ci4/Dockerfile
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    environment:
      CI_ENVIRONMENT: development
      DB_HOST: mysql
      DB_DATABASE: ci4
      DB_USERNAME: root
      DB_PASSWORD: root

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ci4
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

volumes:
  mysql-data:
